### ISSUE TITLE
Task A

### ISSUE THREAD

**Issue by microseyuyu** [microseyuyu/microseyuyu-wiki-docs#16]
整理 microseyuyu-wiki-docs/Test\ Paper/finished 路径下的 README.md
要求 :
- 去除最右侧 RAW 的所有 ".docx" 仅保留 RAW 编号
- 根据现有的 RAW 文件夹下的 RAW 补充进 README.md

**Comment by forward0910** [comment]
根据现有的 RAW 文件夹下的 RAW 补充进 README.md

这条啥意思？

**Comment by microseyuyu** [comment]
就是将 RAW 文件夹下新增的 RAW 文件的编号补充进 README.md
