### ISSUE TITLE
非文本样式的内容无法进行编写

### ISSUE THREAD

**Issue by whyukp** [microseyuyu/microseyuyu-wiki-docs#22]
尝试使用WPS和libreoffice打开，呈现的内容皆为图片形式，图片形式无法在typora上进行编写

**Comment by microseyuyu** [comment]
能否提供更多信息, 例如详细的图片之类的

**Comment by whyukp** [comment]
![image](https://github.com/microseyuyu/microseyuyu-wiki-docs/assets/121537860/3a0d63f9-a3e6-4b3d-8d75-60da9c481c4b)
![image](https://github.com/microseyuyu/microseyuyu-wiki-docs/assets/121537860/bc5ffb9d-355b-493a-a1e4-df22973fe577)

**Comment by microseyuyu** [comment]
请问对应的 RAW 编码是多少

**Comment by whyukp** [comment]
37.docx

**Comment by microseyuyu** [comment]
请跳过这个文档
